name: nowlib_peminjam
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: 5.4.1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  intl: ^0.19.0
  curved_labeled_navigation_bar: ^2.0.2
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  flutter: 
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/giff/
    - assets/image/

